name: weight_track_app
description: The weight track app, now written in flutter
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  custom_navigator:
  google_fonts:
  sqflite: ^1.0.0
  path_provider: ^1.4.0
  fluttertoast: ^7.1.6
  shared_preferences:
  flutter_svg:
  fl_chart:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.svg
